# swagger/v1/main.yaml
openapi: 3.0.3
info:
  title: Inventory Management API
  description: API for inventory management and sales system
  version: 1.0.0
  contact:
    name: API Support
    email: support@company.com

servers:
  - url: http://localhost:3000/api/v1
    description: Development server
  - url: https://api.company.com/v1
    description: Production server

paths:
  # Operational endpoints
  /products:
    $ref: './operational/catalog/products.yaml#/paths/~1products'
  /products/{id}:
    $ref: './operational/catalog/products.yaml#/paths/~1products~1{id}'
  
  # Sales endpoints
  /orders:
    $ref: './sales/orders/orders.yaml#/paths/~1orders'
  /checkout:
    $ref: './sales/orders/checkout.yaml#/paths/~1checkout'
  
  # Analytics endpoints
  /reports:
    $ref: './analytics/reports/reports.yaml#/paths/~1reports'

components:
  schemas:
    $ref: './components/schemas/common.yaml#/components/schemas'
  responses:
    $ref: './components/responses/errors.yaml#/components/responses'
  parameters:
    $ref: './components/parameters/pagination.yaml#/components/parameters'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []