openapi: 3.0.0
info:
  title: Products API
  description: APIs for managing products and categories.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server
paths:
  /products:
    get:
      summary: Fetch products
      description: Retrieve a list of all products.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: integer
                        name:
                          type: string
                        category_id:
                          type: integer
                        manufacturer:
                          type: string
                        sale_price:
                          type: number
                          format: float
                        is_active:
                          type: boolean
  /product-categories:
    get:
      summary: Fetch product categories
      description: Retrieve a list of all product categories.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        category_id:
                          type: integer
                        name:
                          type: string
                        parent_category_id:
                          type: integer
                        is_active:
                          type: boolean
