openapi: 3.0.0
info:
  title: Suppliers API
  description: APIs for managing suppliers.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server
paths:
  /suppliers:
    get:
      summary: Fetch suppliers
      description: Retrieve a list of all suppliers.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        supplier_id:
                          type: integer
                        name:
                          type: string
                        business_name:
                          type: string
                        phone:
                          type: string
                        email:
                          type: string
                        is_active:
                          type: boolean
