openapi: 3.0.0
info:
  title: Users API
  description: APIs for managing users.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server
paths:
  /users:
    get:
      summary: Fetch users
      description: Retrieve a list of all users.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: integer
                        username:
                          type: string
                        full_name:
                          type: string
                        email:
                          type: string
                        role:
                          type: string
                        is_active:
                          type: boolean
